### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: train/cold_start/examples/deepspeed/ds_z3_config.json

### dataset
dataset: vision_r1_llava_cot_full, vision_r1_mulberry_sft_full
dataset_dir: /path/of/vision_r1_cold
template: qwen2_vl
cutoff_len: 16384
overwrite_cache: true
preprocessing_num_workers: 128

### output
output_dir: vision_r1_full_Qwen2.5-VL-7B-Instruct_sft_epoch2_lr5e6_warm005_8GPU
logging_steps: 1
save_steps: 1000
save_total_limit: 2
save_only_model: true
save_strategy: 'steps'
plot_loss: true
overwrite_output_dir: true
report_to: wandb
run_name: vision_r1_full_Qwen2.5-VL-7B-Instruct_sft_epoch2_lr5e6_warm005_8GPU


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
# weight_decay: 1.0e-4
num_train_epochs: 2
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 540000000

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: 'no'
eval_steps: 10000000
